### ISSUE TITLE
Add protobuf wrappers support

### ISSUE THREAD

**Issue by singgel** [BAData/protobuf-converter#18]
**change:**
`message PrimitiveTest {
    int32 intValue = 1;
    int64 longValue = 2;
    float floatValue = 3;
	google.protobuf.DoubleValue doubleValue = 4;
    bool booleanValue = 5;
}`

**exception:**
`java.lang.IllegalArgumentException: argument type mismatch

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.badata.protobuf.converter.writer.DomainWriter.writeValue(DomainWriter.java:51)
	at net.badata.protobuf.converter.writer.DomainWriter.write(DomainWriter.java:44)
	at net.badata.protobuf.converter.writer.AbstractWriter.write(AbstractWriter.java:34)
	at net.badata.protobuf.converter.Converter.fillDomainField(Converter.java:192)
	at net.badata.protobuf.converter.Converter.fillDomain(Converter.java:158)
	at net.badata.protobuf.converter.Converter.toDomain(Converter.java:121)
	at net.badata.protobuf.converter.Converter.fillDomainField(Converter.java:182)
	at net.badata.protobuf.converter.Converter.fillDomain(Converter.java:158)
	at net.badata.protobuf.converter.Converter.toDomain(Converter.java:121)
	at net.badata.protobuf.converter.ConverterTest.testProtobufToDomain(ConverterTest.java:117)`

**Comment by singgel** [comment]
I tested the performance and found it was inefficient.😟
